version: '3.1'

services:
  sql_server:
    container_name: SQLServer2022
    build:
      context: .
      target: SQL2022
    ports:
      - '1433:1433'
    volumes:
      - ./file_db/SQLServer/:/var/opt/mssql/data/
    restart: always
